### ISSUE TITLE
Crash with OpenCL imagepipeline

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#126]
LuxCore built from commit 5ca348708fc0a0b4b91e51c7473730cbc11e6515
OS: Windows 7 64 bit

LuxCore crashes with any renderengine (CPU or OpenCL doesn't matter) when 
the OpenCL imagepipeline is enabled.
If I force the pipeline to use CPU with `film.opencl.enable = 0`, everything works.

Log output:
```
F:\Users\Simon_2>"C:\Program Files\Blender Foundation\Blender\blender.exe"
Read prefs: F:\Users\Simon_2\AppData\Roaming\Blender Foundation\Blender\2.79\con
fig\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
pyluxcore version: 2.1alpha3
[Engine/Viewport] view_update
[Engine/Viewport] New session
[Exporter] create_session
[SDL][7.036] Camera type: perspective
[SDL][7.036] Camera position: Point[7.30805, -7.14744, 5.54845]
[SDL][7.036] Camera target: Point[6.67972, -6.53292, 5.07141]
[SDL][7.036] Camera clipping plane disabled
[SDL][7.036] Material definition: 78330984_AREA_LIGHT_MAT
[SDL][7.036] The 78330984 object is a light sources with 2 triangles
[SDL][7.036] Scene objects count: 1
[SDL][7.036] Light definition: __WORLD_BACKGROUND_LIGHT__
[LuxCore][7.099] Configuration:
[LuxCore][7.099]   path.pathdepth.total = 7
[LuxCore][7.099]   path.pathdepth.diffuse = 5
[LuxCore][7.099]   path.pathdepth.glossy = 5
[LuxCore][7.099]   path.pathdepth.specular = 6
[LuxCore][7.099]   rtpathcpu.zoomphase.size = 4
[LuxCore][7.099]   rtpathcpu.zoomphase.weight = 0
[LuxCore][7.099]   scene.epsilon.max = 0.10000000149011612
[LuxCore][7.099]   film.width = 1612
[LuxCore][7.099]   sampler.type = "RTPATHCPUSAMPLER"
[LuxCore][7.099]   film.filter.type = "BLACKMANHARRIS"
[LuxCore][7.099]   renderengine.type = "RTPATHCPU"
[LuxCore][7.099]   film.height = 965
[LuxCore][7.099]   film.filter.width = 1.5
[LuxCore][7.099]   lightstrategy.type = "LOG_POWER"
[LuxCore][7.099]   scene.epsilon.min = 9.9999997473787516e-06
[LuxCore][7.099]   path.forceblackbackground.enable = 0
[LuxCore][7.099]   renderengine.seed = 1
[LuxCore][7.099]   film.imagepipelines.0.0.type = "NOP"
[LuxCore][7.099]   film.imagepipelines.0.1.type = "TONEMAP_AUTOLINEAR"
[LuxCore][7.099]   film.imagepipelines.0.2.type = "TONEMAP_LINEAR"
[LuxCore][7.099]   film.imagepipelines.0.2.scale = 0.5
[LuxCore][7.099]   batch.haltthreshold.stoprendering.enable = 0
[LuxCore][7.099]   batch.haltthreshold = 0.0001
[LuxCore][7.099]   batch.haltspp = 0
[LuxCore][7.099]   batch.halttime = 0
Export took 0.1 s
[LuxCore][7.099] Film resolution: 1612x965
[SDL][7.099] Film output definition: RGB_IMAGEPIPELINE [image.png]
[SDL][7.099] Image pipeline: film.imagepipelines.0
[SDL][7.099] Image pipeline step 0: NOP
[SDL][7.114] Image pipeline step 1: TONEMAP_AUTOLINEAR
[SDL][7.114] Image pipeline step 2: TONEMAP_LINEAR
[LuxRays][7.130] OpenCL Platform 0: Advanced Micro Devices, Inc.
[LuxRays][7.130] Device 0 name: NativeThread
[LuxRays][7.130] Device 0 type: NATIVE_THREAD
[LuxRays][7.130] Device 0 compute units: 1
[LuxRays][7.130] Device 0 preferred float vector width: 4
[LuxRays][7.130] Device 0 max allocable memory: 0MBytes
[LuxRays][7.130] Device 0 max allocable memory block size: 0MBytes
[LuxRays][7.130] Device 1 name: Tahiti
[LuxRays][7.130] Device 1 type: OPENCL_GPU
[LuxRays][7.130] Device 1 compute units: 32
[LuxRays][7.130] Device 1 preferred float vector width: 1
[LuxRays][7.130] Device 1 max allocable memory: 3072MBytes
[LuxRays][7.130] Device 1 max allocable memory block size: 2393MBytes
[LuxRays][7.130] Device 2 name: AMD Phenom(tm) II X6 1055T Processor
[LuxRays][7.130] Device 2 type: OPENCL_CPU
[LuxRays][7.130] Device 2 compute units: 6
[LuxRays][7.130] Device 2 preferred float vector width: 4
[LuxRays][7.130] Device 2 max allocable memory: 12284MBytes
[LuxRays][7.130] Device 2 max allocable memory block size: 3071MBytes
[LuxRays][7.130] Creating 6 intersection device(s)
[LuxRays][7.130] Allocating intersection device 0: NativeThread (Type = NATIVE_T
HREAD)
[LuxRays][7.130] Allocating intersection device 1: NativeThread (Type = NATIVE_T
HREAD)
[LuxRays][7.130] Allocating intersection device 2: NativeThread (Type = NATIVE_T
HREAD)
[LuxRays][7.130] Allocating intersection device 3: NativeThread (Type = NATIVE_T
HREAD)
[LuxRays][7.130] Allocating intersection device 4: NativeThread (Type = NATIVE_T
HREAD)
[LuxRays][7.130] Allocating intersection device 5: NativeThread (Type = NATIVE_T
HREAD)
[LuxCore][7.130] Configuring 6 CPU render threads
[LuxRays][7.130] Preprocessing DataSet
[LuxRays][7.130] Total vertex count: 4
[LuxRays][7.130] Total triangle count: 2
[LuxRays][7.130] Preprocessing DataSet done
[LuxRays][7.130] Adding DataSet accelerator: EMBREE
[LuxRays][7.130] Total vertex count: 4
[LuxRays][7.130] Total triangle count: 2
[LuxRays][7.145] EmbreeAccel build time: 0ms
[LuxCore][7.457] Film OpenCL image pipeline
[LuxCore][7.457] Film OpenCL Device used: Tahiti Intersect
[LuxCore][7.457]   Device OpenCL version: OpenCL 1.2 AMD-APP (2580.6)
[LuxRays][7.707] [Device Tahiti Intersect] IMAGEPIPELINE buffer size: 18229Kbyte
s
[LuxRays][7.723] [Device Tahiti Intersect] Merge buffer size: 24305Kbytes
Error: EXCEPTION_ACCESS_VIOLATION
```

**Comment by Dade916** [comment]
I'm not able to reproduce the problem. It works fine here, even under Valgrind. Doe the following command crash for you ?

`bin/luxcoreconsole -D renderengine.type PATHCPU -D sampler.type SOBOL -D batch.haltspp 1 scenes/cornell/cornell.cfg`

Is your OpenCL installation working fine ?

**Comment by Theverat** [comment]
> Does the following command crash for you?

I travelled to my parents today, so I can no longer test on the same machine.
But I guess the command should also crash, as I said it happens with any scene and any renderengine (CPU or OpenCL).

> Is your OpenCL installation working fine?

Since I could render with OpenCL engines just fine if the OpenCL imagepipeline was disabled, I think so.

I will try to install OpenCL on the Linux system I have here and see if I can reproduce it there.
Have you tried on Windows? Maybe it's an OS- or driver-specific problem?
My Windows machine has an HD 7970 GHz GPU.

**Comment by Dade916** [comment]
I tried on Linux and Windows, standalone and with Blender but no crash at all here.

**Comment by Dade916** [comment]
Any news ?

**Comment by Theverat** [comment]
Not really. I tried to install OpenCL on my notebook, but it seems to be some crappy outdated version that throws assertion errors all over the place (not bugs in LuxCore, but in the OpenCL installation).

In the last days I looked into other topics (e.g. disney principled shader) and my motivation for this issue was rather low.
Can we just leave this open until I look into it?
By the way, do you think this is related? https://forums.luxcorerender.org/viewtopic.php?f=4&t=569#p5610

**Comment by Dade916** [comment]
> Can we just leave this open until I look into it?

Ok

> By the way, do you think this is related? https://forums.luxcorerender.org/viewtopic.php?f=4&t=569#p5610

I asked if it happens also with alpha3 binaries and he wrote it does so must be a different problem (likely on his PC because it happens only to him with alpha3).

**Comment by Theverat** [comment]
Got my OpenCL to work, here's a backtrace.
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffdb5848cc in slg::Film::WriteAllOCLBuffers() () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
(gdb) bt
#0  0x00007fffdb5848cc in slg::Film::WriteAllOCLBuffers() () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#1  0x00007fffdb5827a7 in slg::Film::ExecuteImagePipelineImpl(unsigned int) () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#2  0x00007fffdb5827d4 in slg::Film::ExecuteImagePipeline(unsigned int) () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#3  0x00007fffdb571508 in slg::Film::RunHaltTests() () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#4  0x00007fffdb34b69b in slg::RenderEngine::UpdateFilm() () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#5  0x00007fffdb2ede9c in luxcore::detail::RenderSessionImpl::UpdateStats() () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#6  0x00007fffdb29f586 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (luxcore::detail::RenderSessionImpl::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, luxcore::detail::RenderSessionImpl&> > >::operator()(_object*, _object*) () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#7  0x00007fffdc1a67dc in boost::python::objects::function::call(_object*, _object*) const () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#8  0x00007fffdc1a6b38 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
   from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#9  0x00007fffdc1afbf3 in boost::python::handle_exception_impl(boost::function0<void>) () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#10 0x00007fffdc1a5449 in function_call () from /home/simon/.config/blender/2.79/scripts/addons/BlendLuxCore/bin/pyluxcore.so
#11 0x0000000002e4f06c in PyObject_Call ()
#12 0x0000000002f123a2 in PyEval_EvalFrameEx ()
#13 0x0000000002f1869e in ?? ()
#14 0x0000000002f1581a in PyEval_EvalFrameEx ()
#15 0x0000000002f1869e in ?? ()
#16 0x0000000002f18773 in PyEval_EvalCodeEx ()
#17 0x0000000002e79674 in ?? ()
#18 0x0000000002e4f06c in PyObject_Call ()
#19 0x0000000001472964 in ?? ()
#20 0x00000000019a7a51 in ?? ()
#21 0x0000000001155704 in view3d_main_region_draw ()
#22 0x0000000001357b1d in ED_region_do_draw ()
#23 0x000000000107d535 in wm_draw_update ()
#24 0x0000000001078f88 in WM_main ()
#25 0x0000000001016a38 in main ()
```

**Comment by Theverat** [comment]
I found a bug and fixed it, now everything works on my notebook:
https://github.com/LuxCoreRender/LuxCore/commit/1d8a983cbfb3c8e34e35e44605aebfa2c31e14a2

It was the rather special case that OpenCL was enabled, but the only intersection device is my CPU, so the imagepipeline does not use it because it only looks for GPU devices.

Not sure if this was also the problem on my desktop PC, because that PC has a GPU.
