### ISSUE TITLE
OpenCL engines crash when scene contains no lights

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#202]
Scene: [crash_no_lights.zip](https://github.com/LuxCoreRender/LuxCore/files/3177176/crash_no_lights.zip)

gdb Backtrace:
```
[LuxRays][0.097] Allocating intersection device 0:       Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (Type = OPENCL_CPU)
[LuxCore][0.097] OpenCL devices used:
[LuxCore][0.097] [      Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz Intersect]
[LuxCore][0.097]   Device OpenCL version: OpenCL 1.2 (Build 37)
[LuxCore][0.097] Native devices used: 0
[LuxCore][0.097] Configuring 1 OpenCL render threads
[LuxCore][0.097] Configuring 0 native render threads
RenderSession starting error: 
The scene doesn't include any light source (note: volume emission doesn't count for this check)

Thread 1 "luxcoreui" received signal SIGSEGV, Segmentation fault.
0x0000000000eb0cfc in slg::GenericFrameBuffer<4u, 1u, float>::Clear (this=0x0, value=0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/include/slg/film/framebuffer.h:36
36			std::fill(pixels.begin(), pixels.begin() + width * height * CHANNELS, value);
(gdb) bt
#0  0x0000000000eb0cfc in slg::GenericFrameBuffer<4u, 1u, float>::Clear (this=0x0, value=0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/include/slg/film/framebuffer.h:36
#1  0x0000000000ead10a in slg::Film::Clear (this=0x31ca800) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/film/film.cpp:513
#2  0x0000000000b46acc in slg::PathOCLRenderEngine::MergeThreadFilms (this=0x31cb0e0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/engines/pathocl/pathocl.cpp:169
#3  0x0000000000b46c2b in slg::PathOCLRenderEngine::UpdateFilmLockLess (this=0x31cb0e0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/engines/pathocl/pathocl.cpp:187
#4  0x0000000000b0a81d in slg::RenderEngine::Stop (this=0x31cb0e0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/engines/renderengine.cpp:151
#5  0x0000000000c246f2 in slg::RenderSession::Stop (this=0x31cc720) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/rendersession.cpp:89
#6  0x0000000000c245bb in slg::RenderSession::~RenderSession (this=0x31cc720, __in_chrg=<optimized out>) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/slg/rendersession.cpp:62
#7  0x0000000000aa1bf2 in luxcore::detail::RenderSessionImpl::~RenderSessionImpl (this=0x31b4c20, __in_chrg=<optimized out>) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/luxcore/luxcoreimpl.cpp:888
#8  0x0000000000aa1c4a in luxcore::detail::RenderSessionImpl::~RenderSessionImpl (this=0x31b4c20, __in_chrg=<optimized out>) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/src/luxcore/luxcoreimpl.cpp:889
#9  0x00000000009eaa7d in LuxCoreApp::StartRendering (this=0x7ffffffab700, startState=0x0, startFilm=0x0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/samples/luxcoreui/luxcoreapp.cpp:361
#10 0x00000000009f0038 in LuxCoreApp::RunApp (this=0x7ffffffab700, startState=0x0, startFilm=0x0) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/samples/luxcoreui/uiloop.cpp:469
#11 0x00000000009e3e77 in main (argc=2, argv=0x7fffffffe5a8) at /home/simon/Projekte/luxcore_build/LinuxCompile/LuxCore-opencl/samples/luxcoreui/luxcoreui.cpp:222
(gdb)
```

**Comment by Dade916** [comment]
I should have fixed the problem.

**Comment by Theverat** [comment]
Thanks!
