### ISSUE TITLE
pyluxcoreforblender mismatched signature

### ISSUE THREAD

**Issue by Alpistinho** [LuxCoreRender/LuxCore#279]
Hi,

After I've compiled my branch after merging with the latest master, I've been unable to enable the LuxCoreRender on Blender

Using the latest BlendLuxCore, I've got the following error:
```
Traceback (most recent call last):
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/base.py", line 84, in render_final
    final.render(self, depsgraph)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/final.py", line 49, in render
    _render_layer(engine, depsgraph, statistics, layer)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/engine/final.py", line 61, in _render_layer
    engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/export/__init__.py", line 112, in create_session
    if not self.object_cache2.first_run(self, depsgraph, view_layer, engine, luxcore_scene, scene_props, is_viewport_render):
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 67, in first_run
    luxcore_scene, scene_props, is_viewport_render)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 115, in _convert_obj
    luxcore_scene, scene_props, is_viewport_render)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/export/caches/object_cache.py", line 146, in _convert_mesh_obj
    is_viewport_render, use_instancing, transform)
  File "/home/daniel/.config/blender/2.81/scripts/addons/BlendLuxCore/export/mesh_converter.py", line 41, in convert
    material_count)
Boost.Python.ArgumentError: Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, list, list, int)
did not match C++ signature:
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int)
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int, boost::python::api::object)
ERROR: Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, list, list, int)
did not match C++ signature:
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int)
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int, boost::python::api::object)
Error: Python argument types in
    Scene.DefineBlenderMesh(Scene, str, int, int, int, int, int, list, list, int)
did not match C++ signature:
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int)
    DefineBlenderMesh(luxcore::detail::SceneImpl*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned int, boost::python::api::object)
```

The definition is in: https://github.com/LuxCoreRender/LuxCore/blob/044d55f50de67177ff9789398e3712f36fd6b638/include/luxcore/pyluxcore/pyluxcoreforblender.h#L73-L90

I've modified this line and the implementations to match:

```cpp
extern boost::python::list Scene_DefineBlenderMesh1(luxcore::detail::SceneImpl *scene, const std::string &name,
		const size_t loopTriCount, const size_t loopTriPtr,
		const size_t loopPtr,
		const size_t vertPtr,
		const size_t polyPtr,
		const boost::python::list &loopUVsPtrList,
		const boost::python::list &loopColsPtrList,
		const u_int materialCount,
		const boost::python::object &transformation);
		
extern boost::python::list Scene_DefineBlenderMesh2(luxcore::detail::SceneImpl *scene, const std::string &name,
		const size_t loopTriCount, const size_t loopTriPtr,
		const size_t loopPtr,
		const size_t vertPtr,
		const size_t polyPtr,
		const boost::python::list &loopUVsPtrList,
		const boost::python::list &loopColsPtrList,
		const u_int materialCount);
```

Now it is apparently working.

Is that change reasonable? 
I don't know why this was not working for me while working on the Azure build I've downloaded.
My branch is just the one related to the Triplanar Mapping, so I don't I've changed anything related to that

**Comment by neo2068** [comment]
The Scene_DefineBlenderMesh functions have been changed recently in LuxCore due to the multiUV support. boost::python::list is derived from boost::python::object. It should work with the first implementation, too.
The function definition in the error message expects a pointer (unsigned long) at position 8 and 9 which was the old definition. Are you sure that you used the recent pyluxcore.pyd within the BlendluxCore/bin directory? It seems that you combined a recent version of the Blender Addon with an old version of pyluxcore.

**Comment by Alpistinho** [comment]
I have just compiled that and cloned the BlendLuxCore from the repo.

I will double check, I am probably doing something stupid

**Comment by Alpistinho** [comment]
I've compiled everything again and it appears to be working now. I probably messed up something

Thanks
