### ISSUE TITLE
[SOLVED] [not updated GPU drivers] [OPEN_CL] metal anisotropy + Glossy clearcoat, instant crash

### ISSUE THREAD

**Issue by mjutrzenka** [LuxCoreRender/LuxCore#316]
Simple problem basically.. when u are doing shader metal anisotropy with glossy clearcoat it crashes on GPU... in my case.. Windows 10 GTX 1070.
Blender 2.82 & 2.3 lux
[LUX_BUG_CRASH.zip](https://github.com/LuxCoreRender/LuxCore/files/4389914/LUX_BUG_CRASH.zip)

**Comment by Theverat** [comment]
It seems to be related to the "Height.tif" texture. When I remove it, no crash happens.
It's also not related to OpenCL, it crashes on CPU as well.

Here's a gdb backtrace of the crash (done with Blender 2.82a, Lux v2.4alpha0 on Ubuntu 19.10):
```
(gdb) bt
#0  0x00007ffff77cbe89 in __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:498
#1  0x0000000007b5192b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#2  0x00007fffbdc20c8f in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_try_char() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#3  0x00007fffbdc2c7c6 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_atom() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#4  0x00007fffbdc2d2e8 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#5  0x00007fffbdc2d45c in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_disjunction() ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#6  0x00007fffbdc2dbb1 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#7  0x00007fffbdc0fef7 in OpenImageIO_v1_8::ImageSpec::erase_attribute(OpenImageIO_v1_8::string_view, OpenImageIO_v1_8::TypeDesc, bool) () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#8  0x00007fffbdefa957 in OpenImageIO_v1_8::TIFFInput::readspec(bool) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#9  0x00007fffbdefb028 in OpenImageIO_v1_8::TIFFInput::seek_subimage(int, int, OpenImageIO_v1_8::ImageSpec&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#10 0x00007fffbdefb875 in OpenImageIO_v1_8::TIFFInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v1_8::ImageSpec&, OpenImageIO_v1_8::ImageSpec const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#11 0x00007fffbdcd5f6f in OpenImageIO_v1_8::ImageInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v1_8::ImageSpec const*) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#12 0x00007fffbd37e10b in slg::ImageMap::ImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#13 0x00007fffbd3a3b81 in slg::ImageMapCache::GetImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::ChannelSelectionType, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#14 0x00007fffbd3d7c3f in slg::Scene::CreateTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#15 0x00007fffbd3e2e28 in slg::Scene::ParseTextures(luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#16 0x00007fffbd3ebf26 in slg::Scene::Parse(luxrays::Properties const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#17 0x00007fffbd2310ff in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (luxcore::detail::SceneImpl::*)(luxrays::Properties const&), boost::python::default_call_policies, boost::mpl::vector3<void, luxcore::detail::SceneImpl&, luxrays::Properties const&> > >::operator()(_object*, _object*) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#18 0x00007fffbe58109d in boost::python::objects::function::call(_object*, _object*) const ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#19 0x00007fffbe5811f8 in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#20 0x00007fffbe5885b3 in boost::python::handle_exception_impl(boost::function0<void>) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#21 0x00007fffbe57ea09 in function_call ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#22 0x0000000005d48c44 in _PyObject_FastCallKeywords ()
#23 0x0000000001652612 in _PyEval_EvalFrameDefault ()
#24 0x0000000005dfa4bc in _PyEval_EvalCodeWithName ()
#25 0x0000000005d485a6 in _PyFunction_FastCallKeywords ()
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x00000000016538f2 in _PyEval_EvalFrameDefault ()
#27 0x000000000164a720 in  ()
#28 0x000000000165449e in _PyEval_EvalFrameDefault ()
#29 0x000000000164a720 in  ()
#30 0x00000000016540ac in _PyEval_EvalFrameDefault ()
#31 0x000000000164a720 in  ()
#32 0x00000000016540ac in _PyEval_EvalFrameDefault ()
#33 0x000000000164a720 in  ()
#34 0x0000000005d484e6 in _PyFunction_FastCallDict ()
#35 0x0000000001b47dae in  ()
#36 0x0000000001ada641 in  ()
#37 0x00000000057ac6f5 in RE_engine_render ()
#38 0x00000000057b64a1 in  ()
#39 0x00000000057b91f0 in  ()
#40 0x00000000057b9b5e in RE_RenderFrame ()
#41 0x0000000002a143f7 in  ()
#42 0x000000000182eef2 in  ()
#43 0x00007ffff7f89669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#44 0x00007ffff775f323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by mjutrzenka** [comment]
i just had crash of just simple matte shader with glossy coating... seams like glossy coating is crashing.
