### ISSUE TITLE
Crash when loading .tif file

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#345]
Scene: https://www.dropbox.com/s/qwbonde9n770mbs/tif_crash.zip?dl=1
OS: Ubuntu 19.10.

To reproduce, open the file and press F12.

I'm not sure if this is a bug in Lux, in OIIO, or if there's a problem introduced during compilation.
Can you reproduce it?
The crash seems to happen in `ImageInput::open(resolvedFileName, &config)`:
https://github.com/LuxCoreRender/LuxCore/blob/60b1c037c6135d9ca5ab8631b8f8bd5cc54b3914/src/slg/imagemap/imagemap.cpp#L677

Here's a gdb backtrace:

```
(gdb) bt
#0  0x00007ffff77c9e93 in __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:500
#1  0x0000000007b5192b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#2  0x00007fffbe127ecf in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_try_char() () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#3  0x00007fffbe135bdc in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_atom() () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#4  0x00007fffbe1362f8 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative() () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#5  0x00007fffbe136550 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_disjunction() () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#6  0x00007fffbe136c97 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#7  0x00007fffbe114e41 in OpenImageIO_v1_8::ImageSpec::erase_attribute(OpenImageIO_v1_8::string_view, OpenImageIO_v1_8::TypeDesc, bool) () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#8  0x00007fffbe3eb768 in OpenImageIO_v1_8::TIFFInput::readspec(bool) () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#9  0x00007fffbe3ebe8d in OpenImageIO_v1_8::TIFFInput::seek_subimage(int, int, OpenImageIO_v1_8::ImageSpec&) () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#10 0x00007fffbe3ec40a in OpenImageIO_v1_8::TIFFInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v1_8::ImageSpec&, OpenImageIO_v1_8::ImageSpec const&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#11 0x00007fffbe1e408f in OpenImageIO_v1_8::ImageInput::open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, OpenImageIO_v1_8::ImageSpec const*) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#12 0x00007fffbda81a9e in slg::ImageMap::ImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType)
    (this=0x7fffa97cea40, fileName=..., g=<optimized out>, storageType=slg::ImageMapStorage::AUTO, wrapType=slg::ImageMapStorage::REPEAT) at /home/simon/Projects/LinuxCompile/LuxCore-opencl/src/slg/imagemap/imagemap.cpp:677
#13 0x00007fffbda96d72 in slg::ImageMapCache::GetImageMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float, slg::ImageMapStorage::ChannelSelectionType, slg::ImageMapStorage::StorageType, slg::ImageMapStorage::WrapType)
    (this=this@entry=0x7fffa97d2188, fileName="/home/simon/Downloads/tif_crash/image.tif", gamma=gamma@entry=2.20000005, selectionType=selectionType@entry=slg::ImageMapStorage::DEFAULT, storageType=storageType@entry=slg::ImageMapStorage::AUTO, wrapType=wrapType@entry=slg::ImageMapStorage::REPEAT) at /home/simon/Projects/LinuxCompile/LuxCore-opencl/src/slg/imagemap/imagemapcache.cpp:83
#14 0x00007fffbdac41f3 in slg::Scene::CreateTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, luxrays::Properties const&)
    (this=0x7fffa97d2000, texName="140735673712648Color", props=...) at /home/simon/Projects/LinuxCompile/LuxCore-opencl/src/slg/scene/parsetextures.cpp:154
#15 0x00007fffbdace839 in slg::Scene::ParseTextures(luxrays::Properties const&) (this=this@entry=0x7fffa97d2000, props=...) at /home/simon/Projects/LinuxCompile/LuxCore-opencl/src/slg/scene/parsetextures.cpp:111
#16 0x00007fffbdad5fc4 in slg::Scene::Parse(luxrays::Properties const&) (this=0x7fffa97d2000, props=...) at /home/simon/Projects/LinuxCompile/LuxCore-opencl/src/slg/scene/scene.cpp:305
#17 0x00007fffbd97335b in boost::python::detail::invoke<int, void (luxcore::detail::SceneImpl::*)(luxrays::Properties const&), boost::python::arg_from_python<luxcore::detail::SceneImpl&>, boost::python::arg_from_python<luxrays::Properties const&> >(boost::python::detail::invoke_tag_<true, true>, int const&, void (luxcore::detail::SceneImpl::*&)(luxrays::Properties const&), boost::python::arg_from_python<luxcore::detail::SceneImpl&>&, boost::python::arg_from_python<luxrays::Properties const&>&) (ac0=..., tc=<synthetic pointer>..., f=<optimized out>) at /home/simon/Projects/LinuxCompile/target-64-sse2/include/boost/python/converter/arg_from_python.hpp:310
#18 0x00007fffbd97335b in boost::python::detail::caller_arity<2u>::impl<void (luxcore::detail::SceneImpl::*)(luxrays::Properties const&), boost::python::default_call_policies, boost::mpl::vector3<void, luxcore::detail::SceneImpl&, luxrays::Properties const&> >::operator()(_object*, _object*) (args_=<optimized out>, this=<optimized out>) at /home/simon/Projects/LinuxCompile/target-64-sse2/include/boost/python/detail/caller.hpp:216
#19 0x00007fffbd97335b in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (luxcore::detail::SceneImpl::*)(luxrays::Properties const&), boost::python::default_call_policies, boost::mpl::vector3<void, luxcore::detail::SceneImpl&, luxrays::Properties const&> > >::operator()(_object*, _object*) (this=<optimized out>, args=<optimized out>, kw=<optimized out>)
    at /home/simon/Projects/LinuxCompile/target-64-sse2/include/boost/python/object/py_function.hpp:38
#20 0x00007fffbeaaaa9d in boost::python::objects::function::call(_object*, _object*) const () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#21 0x00007fffbeaaac4c in boost::detail::function::void_function_ref_invoker0<boost::python::objects::(anonymous namespace)::bind_return, void>::invoke(boost::detail::function::function_buffer&) ()
    at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#22 0x00007fffbeab13c3 in boost::python::handle_exception_impl(boost::function0<void>) () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#23 0x00007fffbeaa92a6 in function_call () at /home/simon/.config/blender/2.82/scripts/addons/BlendLuxCore_git/bin/pyluxcore.so
#24 0x0000000005d48c44 in _PyObject_FastCallKeywords ()
#25 0x0000000001652612 in _PyEval_EvalFrameDefault ()
#26 0x0000000005dfa4bc in _PyEval_EvalCodeWithName ()
#27 0x0000000005d485a6 in _PyFunction_FastCallKeywords ()
#28 0x00000000016538f2 in _PyEval_EvalFrameDefault ()
#29 0x000000000164a720 in  ()
#30 0x000000000165449e in _PyEval_EvalFrameDefault ()
#31 0x000000000164a720 in  ()
#32 0x00000000016540ac in _PyEval_EvalFrameDefault ()
#33 0x000000000164a720 in  ()
#34 0x00000000016540ac in _PyEval_EvalFrameDefault ()
#35 0x000000000164a720 in  ()
#36 0x0000000005d484e6 in _PyFunction_FastCallDict ()
#37 0x0000000001b47dae in  ()
#38 0x0000000001ada641 in  ()
#39 0x00000000057ac6f5 in RE_engine_render ()
#40 0x00000000057b64a1 in  ()
```

**Comment by Dade916** [comment]
The scene is working fine here with the latest version. Does it still crash for you ?

**Comment by Theverat** [comment]
Yes. I also noticed crashes with EXR files.
If it works on your Ubuntu, it's probably some problem with my compilation process. I'll have to redo that anyway to get CUDA running, I'll check afterwards if the problem persists.

**Comment by Dade916** [comment]
I applied a couple of patches to OIIO in our LinuxCompileDeps repository, you may have problems if you use the system installed version instead than our one.
