### ISSUE TITLE
OpenCL driver API error (code: -1001)

### ISSUE THREAD

**Issue by dadaromeo** [LuxCoreRender/LuxCore#422]
.blend file: 

Steps to reproduce:

Screenshots or rendered images:
![Screenshot_2020-07-30_14-12-51](https://user-images.githubusercontent.com/5675732/88927102-da5d3b00-d26e-11ea-8a29-2bea8591a115.png)

Error message from Blender console: Traceback (most recent call last):
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/handlers/load_post.py", line 59, in handler
    updated = scene.luxcore.devices.update_devices_if_necessary()
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 41, in update_devices_if_necessary
    device_props = self.get_device_props()
  File "/home/romeo/.config/blender/2.83/scripts/addons/BlendLuxCore/properties/devices.py", line 99, in get_device_props
    return pyluxcore.GetOpenCLDeviceDescs()
RuntimeError: OpenCL driver API error (code: -1001, file:/home/vsts/work/1/s/LinuxCompile/LuxCore/src/luxrays/devices/ocldevice.cpp, line: 72): -1001

OS: UbuntuStudio 20.04
Blender version: 2.83
LuxCore version: 2.4

**Comment by Dade916** [comment]
I should have fixed this case in v2.5.
