### ISSUE TITLE
Optix Denoiser Error (code: 7001)

### ISSUE THREAD

**Issue by kintuX** [LuxCoreRender/LuxCore#430]
Latest LuxCore build **94b1f5ccd**

Just starting rendered preview, reports an error:

```
Traceback (most recent call last):
  File "C:\Users\309\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\engine\base.py", line 124, in view_draw
    viewport.view_draw(self, context, depsgraph)
  File "C:\Users\309\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\engine\viewport.py", line 221, in view_draw
    framebuffer.update(engine.session, scene)
  File "C:\Users\309\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore\draw\viewport.py", line 229, in update
    luxcore_session.GetFilm().GetOutputFloat(self._output_type, self.buffer)
RuntimeError: Optix error (code: 7001, file:c:\luxcorerender\luxcore\src\slg\film\imagepipeline\plugins\optixdenoiser.cpp, line: 110): OPTIX_ERROR_INVALID_VALUE

[LuxCore][19.078] [GeForce GTX 1070 CUDAIntersect] Memory used for hardware image pipeline: 50840Kbytes
```

**Comment by Dade916** [comment]
I know what it is, going to fix it tomorrow (it is a problem with no-RTX card+Optix Denoiser).

**Comment by Dade916** [comment]
I should have fixed the problem.
