### ISSUE TITLE
Syntax error in texture name: *numbers*Color

### ISSUE THREAD

**Issue by Mirxku** [LuxCoreRender/LuxCore#436]
So, i dont even have this texture, and also if i trying to render not in viewport, i got like billions of memory usage (1250 M), and the same error. Why? Also in some scenes it is trying to render without textures, all just white. Any help pls)

**Comment by Dade916** [comment]
Can you post a test scene that trigger this error ?

**Comment by Mirxku** [comment]
> Can you post a test scene that trigger this error ?

what you mean under test scene? It is a scene with character, so it will be pretty big, this error is causing only this character

**Comment by Dade916** [comment]
Try to delete as much stuff as possible from the scene and still have the error. I can not investigate a problem I can not see.

**Comment by Mirxku** [comment]
> Try to delete as much stuff as possible from the scene and still have the error. I can not investigate a problem I can not see.

so, while i was deleting stuff from character, i noticed that i have different texture names in errors, so, can you handle 190mb of blend file, and 140mb of textures if you need em ofc

**Comment by Dade916** [comment]
I can.

**Comment by Mirxku** [comment]
Here: https://drive.google.com/file/d/1IE3U6Ml8-ek5_3aXCc73KO9t2if6QHtV/view?usp=sharing And thanks for help again )

**Comment by Theverat** [comment]
A full error log from Blender's console might also help us.

**Comment by Mirxku** [comment]
I made that all can download it

**Comment by Theverat** [comment]
Are you sure you sent the right file?
The render engine is set to Eevee. Even if I set it to LuxCore, none of the materials seem to be set up for LuxCore.

Please describe the steps to take to reproduce the problem.

**Comment by Mirxku** [comment]
Wait, where i can enable "use Cycles nodes" i cant find it

**Comment by Theverat** [comment]
> Wait, where i can enable "use Cycles nodes" i cant find it

You can click the "Use Cycles Settings" button in the render settings to use Cycles settings in all materials, lights, world background etc.
Or you can enable "Use Cycles Nodes" in individual materials.

![Capture](https://user-images.githubusercontent.com/1584761/90986008-16d73a80-e580-11ea-87ac-e7b4fa8951ff.PNG)

**Comment by Theverat** [comment]
When I press "Use Cycles settings" and try to render, I get the error you probably also got:

```
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\base.py", line 87, in render_final
    final.render(self, depsgraph)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 48, in render
    _render_layer(engine, depsgraph, statistics, layer)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\engine\final.py", line 60, in _render_layer
    engine.session = engine.exporter.create_session(depsgraph, engine=engine, view_layer=view_layer)
  File "C:\Users\Simon\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\BlendLuxCore_git\export\__init__.py", line 143, in create_session
    luxcore_scene.Parse(scene_props)
RuntimeError: Syntax error in texture name: 1874786963496Color
```
It is most likely a bug in the Cycles node reader. I'll check.
