### ISSUE TITLE
Cannot enable the Lux Core Renderer add-on. Registration error.

### ISSUE THREAD

**Issue by annada-behera** [LuxCoreRender/LuxCore#556]
I installed the ZIP file from https://luxcorerender.org/download/ and now when I try to enable the add-on, I get the following error, 

```
TypeError: PointerProperty(...) expected an RNA type, failed with: RuntimeError: , missing bl_rna attribute from 'RNAMetaPropGroup' instance (may not be registered)

Exception in module register(): /home/annada/.config/blender/2.93/scripts/addons/BlendLuxCore/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/annada/.config/blender/2.93/scripts/addons/BlendLuxCore/__init__.py", line 85, in register
    auto_load.register()
  File "/home/annada/.config/blender/2.93/scripts/addons/BlendLuxCore/auto_load.py", line 31, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "LuxCoreImagepipelineBackgroundImage" registration error: image_user could not register
```

How can I fix this error? Thank you.

OS: Linux
Application: Blender 2.93
GPU Driver: 470.63

**Comment by annada-behera** [comment]
> Supported Blender versions: 2.82 to 2.92. Will not work on 2.93+.
> (Note: you can use an automatic build of the under development v2.6 if you need to use Blender v2.93)

Sorry, I should've just read the instruction on the download page.
