### ISSUE TITLE
pyluxcoretools won't render a bcf file that blendluxcore renders fine

### ISSUE THREAD

**Issue by emogenet** [LuxCoreRender/LuxCore#582]
Hello,

I have a scene in blender 2.93.5
I am running blendluxcore v2.6, github 78ed64744d60f28f03e4a735254b637f2b32973d from Dec 27, 2021
I am on Linux Ubuntu 20.04.4 LTS (focal)
I run Python 3.8
PySide is not installed

The scene renders fine in the blender window in "render preview" mode
It also renders fine when I press F12

However, when I save it to a .bcf file (via LuxCore FileSaver in binary mode) and try to render from the command line using the following command:

`python3 pyluxcoretools.zip console /tmp/luxcore/rampe.lampes_LuxCore/00001.bcf`

I get the error shown below at the end.

It looks like it is deserializing the textures fine but fails to find them after deserialization ...

The BCF file is 220 megs, so I'm not even going to try and attach it to this issue, but you can download it here:

[(220 megs) 00001.bcf ](http://95.217.220.241/00001.bcf)

or alternatively : curl 'http://95.217.220.241/00001.bcf' > 0001.bcf

Here's the error message:

`
    ...
 
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514961290320
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401515433779280
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963742800
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963681360
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963681361
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514961674320
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514961674321
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963758160
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963696720
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963696721
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963773520
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963712080
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.270] Loading serialized mesh: InstanceMesh-1401514963712081
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.271] Loading serialized mesh: InstanceMesh-1401514963788880
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.271] Loading serialized mesh: InstanceMesh-1401514963727440
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.271] Loading serialized mesh: InstanceMesh-1401514963727441
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.271] Loading serialized mesh: InstanceMesh-1401514963558480
    [MainThread][2022-02-25 22:03:36,181] [SDL][0.271] Loading serialized image map: NamedObject
    [MainThread][2022-02-25 22:03:36,215] [SDL][0.304] Loading serialized image map: /tmp/tmptd9ucxy7.jpg
    [MainThread][2022-02-25 22:03:36,943] [SDL][1.032] Loading serialized image map: /tmp/tmpauz_khcz.jpg
    [MainThread][2022-02-25 22:03:37,635] [SDL][1.724] Loading serialized image map: /tmp/tmp37vucemm.jpg
    [MainThread][2022-02-25 22:03:37,904] [SDL][1.993] Loading serialized image map: /tmp/tmpw7ifxune.jpg
    [MainThread][2022-02-25 22:03:38,156] [SDL][2.245] Loading serialized image map: /tmp/tmp7gjmj5q6.jpg
    [MainThread][2022-02-25 22:03:38,379] [SDL][2.468] Loading serialized image map: /tmp/tmpphi5k6wi.jpg
    [MainThread][2022-02-25 22:03:38,657] [SDL][2.747] Loading serialized image map: /tmp/tmp5n1wx7a3.jpg
    [MainThread][2022-02-25 22:03:38,907] [SDL][2.996] Loading serialized image map: /tmp/tmptfqqxtwy.jpg
    [MainThread][2022-02-25 22:03:39,228] [SDL][3.317] Loading serialized image map: /tmp/tmpnnf80nh_.jpg
    [MainThread][2022-02-25 22:03:39,304] [SDL][3.393] Loading serialized image map: /tmp/tmpp71amkyw.jpg
    [MainThread][2022-02-25 22:03:39,608] [SDL][3.698] Loading serialized image map: /tmp/tmpjk6gta4o.png
    [MainThread][2022-02-25 22:03:39,712] [SDL][3.801] Loading serialized image map: /tmp/tmpluiqo88l.png
    [MainThread][2022-02-25 22:03:39,754] [SDL][3.843] Loading serialized image map: /tmp/tmpdrjjezcq.jpg
    [MainThread][2022-02-25 22:03:40,044] [SDL][4.133] Loading serialized image map: /tmp/tmptkna8nr1.jpg
    [MainThread][2022-02-25 22:03:40,310] [SDL][4.399] Loading serialized image map: /tmp/tmpbd69hxcx.jpg
    [MainThread][2022-02-25 22:03:40,641] [SDL][4.730] Loading serialized image map: /tmp/tmpui5vptpg.jpg
    [MainThread][2022-02-25 22:03:40,903] [SDL][4.992] Loading serialized image map: /tmp/tmpoz8exhfy.jpg
    [MainThread][2022-02-25 22:03:41,167] [SDL][5.256] Loading serialized image map: /tmp/tmpx2s6him3.jpg
    [MainThread][2022-02-25 22:03:41,492] [SDL][5.581] Loading serialized image map: /tmp/tmpw_rj90ys.jpg
    [MainThread][2022-02-25 22:03:41,771] [SDL][5.860] Loading serialized image map: /tmp/tmp4p7usivk.jpg
    [MainThread][2022-02-25 22:03:42,024] [SDL][6.113] Loading serialized image map: /tmp/tmpib8w8pub.jpg
    [MainThread][2022-02-25 22:03:42,238] [SDL][6.327] Loading serialized image map: /tmp/tmpf37z8o2j.jpg
    [MainThread][2022-02-25 22:03:42,533] [SDL][6.622] Loading serialized image map: /tmp/tmp0hml596y.jpg
    [MainThread][2022-02-25 22:03:42,789] [SDL][6.878] Loading serialized image map: /tmp/tmpj5ku50io.jpg
    [MainThread][2022-02-25 22:03:43,112] [SDL][7.201] Loading serialized image map: /tmp/tmpbb794svi.jpg
    [MainThread][2022-02-25 22:03:43,425] [SDL][7.514] Loading serialized image map: /tmp/tmpn_bcuvat.jpg
    [MainThread][2022-02-25 22:03:43,677] [SDL][7.766] Loading serialized image map: /tmp/tmpxie_32zj.jpg
    [MainThread][2022-02-25 22:03:44,004] [SDL][8.093] Loading serialized image map: /tmp/tmpwrtrsf88.jpg
    [MainThread][2022-02-25 22:03:44,249] [SDL][8.338] Loading serialized image map: /tmp/tmpncwufp3g.jpg
    [MainThread][2022-02-25 22:03:44,286] [SDL][8.375] Loading serialized image map: /tmp/tmp__57vv1y.jpg
    [MainThread][2022-02-25 22:03:44,328] [SDL][8.417] Loading serialized image map: /tmp/tmparat_sk8.jpg
    [MainThread][2022-02-25 22:03:44,373] [SDL][8.462] Loading serialized image map: /tmp/tmp4_rcu71x.jpg
    [MainThread][2022-02-25 22:03:44,761] [SDL][8.850] Texture definition: 140151096626184Color
    [MainThread][2022-02-25 22:03:44,761] [SDL][8.850] Reading texture map: /tmp/tmptd9ucxy7.jpg
    Traceback (most recent call last):
      File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "pyluxcoretools.zip/__main__.py", line 55, in <module>
      File "pyluxcoretools.zip/pyluxcoretools/pyluxcoreconsole/cmd.py", line 174, in main
        the arguments.  Returns a tuple containing (command, args, line).
      File "pyluxcoretools.zip/pyluxcoretools/pyluxcoreconsole/cmd.py", line 131, in LuxCoreConsole
        self.stdout.flush()
    RuntimeError: ImageMap file doesn't exist: /tmp/tmptd9ucxy7.jpg
`

**Comment by emogenet** [comment]
To try and understand what happens, I straced the pyluxcoretools command.

Turns out after each 'Loading serialized image map:' message is printed, a crapload of data is indeed read from the bcf file, but there seems to be neither an open or a write afterwards.

It eventually gets to a 'stat("/tmp/tmptd9ucxy7.jpg", 0x7ffcfdb47e80)' system call which - unsurprisingly - fails.

**Comment by CodeFHD** [comment]
Closing this issue as part of a review of all issues that had been left open. Reasons:
- The test scene is no longer available. Retest with the latest Blender + LuxCore versions would be required.
- The specific issue has not been reported by anyone else as far as I can see, so no other hints to link to.
