### ISSUE TITLE
pyluxcore.so: undefined symbol: _Py_tracemalloc_config

### ISSUE THREAD

**Issue by d1nuc0m** [LuxCoreRender/LuxCore#590]
PyLuxCoreTools, from release 2.6 on Linux, pyenv 2.3.2, with Python 3.7.13 (installed pyside6, pyside2 with dependencies through pip).
```
$ pyenv shell 3.7.13 && python3 ./pyluxcoretools.zip
Traceback (most recent call last):
  File "/home/d1nuc0m/.pyenv/versions/3.7.13/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/d1nuc0m/.pyenv/versions/3.7.13/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./pyluxcoretools.zip/__main__.py", line 75, in <module>
  File "./pyluxcoretools.zip/pyluxcoretools/pyluxcoremenu/cmd.py", line 39, in <module>
    The data members `self.doc_header', `self.misc_header', and
  File "/home/d1nuc0m/.pyenv/versions/3.7.13/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "./pyluxcoretools.zip/pyluxcoretools/pyluxcorenetnode/ui.py", line 26, in <module>
  File "/home/d1nuc0m/.pyenv/versions/3.7.13/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: ./pyluxcore.so: undefined symbol: _Py_tracemalloc_config
```

**Comment by howetuft** [comment]
It is related to an old version of both Python and pyluxcore.so. Could not reproduce with recent versions, I conclude it's been fixed by the modernization of build system and introduction of wheels.
