### ISSUE TITLE
cannot activate LuxCoreRender v2.8alpha1 on Blender 4.0 on Linux

### ISSUE THREAD

**Issue by luisseyfer** [LuxCoreRender/LuxCore#631]
Hello,
I try to get LuxCore 2.8 running on Blender-4.0.2 without success.
I downloaded luxcorerender-v2.8alpha1-linux64.tar.bz2 from [https://github.com/LuxCoreRender/LuxCore/releases](https://github.com/LuxCoreRender/LuxCore/releases).
First, it is confusing not to get a *.zip archive, since this is what Blender expects for the common addon install process.
Funny enough, 9 months back it obviously was still released as a zip archive. (https://www.youtube.com/watch?v=u50EKV1Wi6U go to 1:10)
So, I copied the extracted LuxCore folder into .../home/kubuntu/APPS/BlenderLauncher/stable/blender-4.0.2-stable.9be62e85b727/4.0/scripts/addons
Blender finds it in Preferences > Addons, but I cannot activate:
```
Traceback (most recent call last):
  File "/home/kubuntu/APPS/BlenderLauncher/stable/blender-4.0.2-stable.9be62e85b727/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/home/kubuntu/APPS/BlenderLauncher/stable/blender-4.0.2-stable.9be62e85b727/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kubuntu/.config/blender/4.0/scripts/addons/BlendLuxCore_280/__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore_280.bin' (/home/kubuntu/.config/blender/4.0/scripts/addons/BlendLuxCore_280/bin/__init__.py)


```
/home/kubuntu/.config/blender/4.0/scripts/addons/BlendLuxCore_280/bin/__init__.py exists, but is empty!
  

The version number seems weird, but ... who cares?
![image](https://github.com/user-attachments/assets/11d4cb8b-83e0-47fd-abce-f2d019673043)

Any hints, how to get this working are very much appreciated.

I would also highly suggest providing zip archives for Blender!

Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-107-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2760QM CPU @ 2.40GHz
Memory: 15.6 GiB of RAM
Graphics Processor: Quadro 3000M/PCIe/SSE2 (eGPU)
Graphics Processor: mGTX 1070 (internal)

**Comment by luisseyfer** [comment]
BTW
/home/kubuntu/.config/blender/3.6/scripts/addons/BlendLuxCore_280/bin/__init__.py exists, but is empty

**Comment by neo2068** [comment]
Hi! As far as I know, the linux release always was a bz2 archive. Only windows release is a zip archive (as shown in the video). Can you check if the issue remains with renamed addon folder name, i.e. keep the name BlendLuxCore?

**Comment by luisseyfer** [comment]
Thanks for your answer. 

If you look through releases you will find that only the last alpha and beta versions for Linux are tarballs. 
Where do you see a *.tar.bz2 in the video? 

I tried renaming both folders. Unfortunately it does not change anything.
```
Traceback (most recent call last):
  File "/home/kubuntu/APPS/BlenderLauncher/stable/blender-4.0.2-stable.9be62e85b727/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/home/kubuntu/APPS/BlenderLauncher/stable/blender-4.0.2-stable.9be62e85b727/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kubuntu/.config/blender/4.0/scripts/addons/BlendLuxCore/__init__.py", line 23, in <module>
    raise Exception(msg + "\n\nImportError: %s" % error) from None
Exception: 

Could not import pyluxcore.

ImportError: cannot import name 'pyluxcore' from 'BlendLuxCore.bin' (/home/kubuntu/.config/blender/4.0/scripts/addons/BlendLuxCore/bin/__init__.py)

```

**Comment by neo2068** [comment]
Ok, I got it now. You downloaded the wrong release files. For the Blender addon, you have to go to [BlendLuxCore](https://github.com/LuxCoreRender/BlendLuxCore/releases). There are zip files for linux. The LuxCore project only has the binaries for standalone use of LuxCoreRender.

**Comment by luisseyfer** [comment]
Ahhh, I see.

**Comment by luisseyfer** [comment]
Ahhh, I see. That solves it. Thanks a lot!
