### ISSUE TITLE
Network render: "Unable to receive a line"

### ISSUE THREAD

**Issue by Theverat** [LuxCoreRender/LuxCore#80]
Hi, 

I did the following:
* start pyluxcoretool in netconsole mode
* add a .bcf file with the "add job" button
* start second pyluxcoretool in netnode mode
* pressed "start node"

After this, both showed errors and were retrying endlessly, but always aborting with the same error.

netconsole:
```
LuxCore 2.0alpha7
NetBeaconReceiver thread started.
Creating single image render farm job: /home/simon/smoke_backlit_LuxCore/00100.bcf
New render farm job: /home/simon/smoke_backlit_LuxCore/00100.bcf
Job file md5: a4a127eabeda8ddcbd085c0a41f124f5
-------------------------------------------------------
Job started: /home/simon/smoke_backlit_LuxCore/00100.bcf
-------------------------------------------------------
Film merge thread started
Discovered new node: 127.0.1.1:18018
Node thread started
Remote node has the same pyluxcore verison
Sending file: /home/simon/smoke_backlit_LuxCore/00100.bcf
Transfered 8.98 Mbytes in 00:00:00 (248.28 Mbytes/sec)
Sending seed: 1
Waiting for node rendering start
Unable to receive a line
Traceback (most recent call last):
  File "/tmp/_MEIeOR82Q/pyluxcoretools.zip/pyluxcoretools/renderfarm/renderfarmjobsingleimage.py", line 423, in NodeThread
    result = socketutils.RecvLine(nodeSocket)
  File "/tmp/_MEIeOR82Q/pyluxcoretools.zip/pyluxcoretools/utils/socket.py", line 44, in RecvLine
    raise RuntimeError("Unable to receive a line")
RuntimeError: Unable to receive a line
Node thread done
Retrying node: 127.0.1.1:18018
Node thread started
Remote node has the same pyluxcore verison
Sending file: /home/simon/smoke_backlit_LuxCore/00100.bcf
Transfered 8.98 Mbytes in 00:00:00 (315.21 Mbytes/sec)
Sending seed: 2
Waiting for node rendering start
Unable to receive a line
Traceback (most recent call last):
  File "/tmp/_MEIeOR82Q/pyluxcoretools.zip/pyluxcoretools/renderfarm/renderfarmjobsingleimage.py", line 423, in NodeThread
    result = socketutils.RecvLine(nodeSocket)
  File "/tmp/_MEIeOR82Q/pyluxcoretools.zip/pyluxcoretools/utils/socket.py", line 44, in RecvLine
    raise RuntimeError("Unable to receive a line")
RuntimeError: Unable to receive a line
Node thread done
Retrying node: 127.0.1.1:18018

[etc.]
```

netnode:
```
LuxCore 2.0alpha7
Waiting for configuration...
NetBeaconSender thread started.
Started
Waiting for a new connection
Received connection from: ('127.0.0.1', 45950)
Remote pyluxcore version: 2.0alpha7
Local pyluxcore version: 2.0alpha7
Receiving RenderConfig serialized file: renderfarmnode-6670e57e-35dd-435f-aa64-ee0e73534db7.bcf
Receiving file: renderfarmnode-6670e57e-35dd-435f-aa64-ee0e73534db7.bcf
Transfered 8.98 Mbytes in 00:00:00 (201.84 Mbytes/sec)
Receiving RenderConfig serialized MD5: a4a127eabeda8ddcbd085c0a41f124f5
Received seed: 1
Reading RenderConfig serialized file: renderfarmnode-6670e57e-35dd-435f-aa64-ee0e73534db7.bcf
[SDL][3.750] Loading serialized mesh: Mesh-Lamp_Area__001_140283443867656
[SDL][3.750] Loading serialized mesh: Mesh-Lamp_Area_140283441027592
[SDL][3.751] Loading serialized mesh: Mesh-Mesh_Smoke__Domain_140283443872264000
[SDL][3.751] Loading serialized image map: LUXCORE_DENSITYGRID_140283433949192
[SDL][5.169] Texture definition: 140283433949192
std::bad_cast
Traceback (most recent call last):
  File "/tmp/_MEIViaFrr/pyluxcoretools.zip/pyluxcoretools/renderfarm/renderfarmnode.py", line 168, in __HandleConnection
    config = pyluxcore.RenderConfig(renderConfigFile)
RuntimeError: std::bad_cast
Connection done: ('127.0.0.1', 45950)
Waiting for a new connection
Received connection from: ('127.0.0.1', 45952)
Remote pyluxcore version: 2.0alpha7
Local pyluxcore version: 2.0alpha7
Receiving RenderConfig serialized file: renderfarmnode-01a1ac45-c861-47d6-bd0d-1ef27d6f405b.bcf
Receiving file: renderfarmnode-01a1ac45-c861-47d6-bd0d-1ef27d6f405b.bcf
Transfered 8.98 Mbytes in 00:00:00 (217.66 Mbytes/sec)
Receiving RenderConfig serialized MD5: a4a127eabeda8ddcbd085c0a41f124f5
Received seed: 2
Reading RenderConfig serialized file: renderfarmnode-01a1ac45-c861-47d6-bd0d-1ef27d6f405b.bcf
[SDL][6.753] Loading serialized mesh: Mesh-Lamp_Area__001_140283443867656
[SDL][6.753] Loading serialized mesh: Mesh-Lamp_Area_140283441027592
[SDL][6.753] Loading serialized mesh: Mesh-Mesh_Smoke__Domain_140283443872264000
[SDL][6.753] Loading serialized image map: LUXCORE_DENSITYGRID_140283433949192
[SDL][8.125] Texture definition: 140283433949192
std::bad_cast
Traceback (most recent call last):
  File "/tmp/_MEIViaFrr/pyluxcoretools.zip/pyluxcoretools/renderfarm/renderfarmnode.py", line 168, in __HandleConnection
    config = pyluxcore.RenderConfig(renderConfigFile)
RuntimeError: std::bad_cast
Connection done: ('127.0.0.1', 45952)
Waiting for a new connection
Received connection from: ('127.0.0.1', 45954)

[etc.]
```

The .bcf file works fine in luxcoreui.
[scene.zip](https://github.com/LuxCoreRender/LuxCore/files/1865435/scene.zip)

Ubuntu 14.04
Do you need additional info?

**Comment by Dade916** [comment]
I have tested the scene here and it is working fine both with luxcoreui and netconsoleui/nodeui. Looking at the error, I have the feeling you may have used different LuxCore versions for saving the .bcf file and running the netnode.

Looking at my netnode output:

```
[Thread-1][2018-03-31 13:57:52,703] [SDL][1.643] Texture definition: 140283433949192
[Thread-1][2018-03-31 13:57:52,861] [SDL][1.801] Define ImageMap: LUXCORE_DENSITYGRID_140283433949192
[Thread-1][2018-03-31 13:57:52,862] [SDL][1.801] Texture definition: Implicit-ConstFloatTexture-a405bc1f-8b5a-415a-89fc-5b16de442baa
[Thread-1][2018-03-31 13:57:52,862] [SDL][1.801] Texture definition: 140283433949704
[Thread-1][2018-03-31 13:57:52,862] [SDL][1.801] Texture definition: 140283433948680_colordepth
[Thread-1][2018-03-31 13:57:52,862] [SDL][1.802] Texture definition: Implicit-ConstFloatTexture-80ce3e21-00fb-4f47-879b-66e81f8e7160
```

The error seems to be triggered exactly by Density Grid texture, like if you were using a netnode without the latest volume rendering code.

**Comment by Dade916** [comment]
Do you still have this problem ?

**Comment by Theverat** [comment]
Yes but if it works on your system then it is most likely again either something I'm doing wrong or something in my system.

I will test it with beta1 and if it works with those binaries we can close this issue.

**Comment by Theverat** [comment]
I tested again with your beta1 binaries but I still have the same problem.
(I used your binaries in Blender to export the scene, so there should be no mismatch).

One thing I noticed: You are probably testing with an OpenCL build, right?
I'm using No-OpenCL on my laptop. Maybe it only happens in builds without OpenCL.

**Comment by Dade916** [comment]
It happens only with executable packed with PyInstaller and only on Linux. Any conversion from string to floating point, doesn't work anymore:

cout << boost::lexical_cast<float>("0.5") << "\n";

My first idea was some mess with LOCALE but:

cout << boost::lexical_cast<float>("0,5") << "\n";

doesn't work too. I'm still convinced it is some kind of LOCALE related mess in PyInstaller/Boost.

**Comment by Dade916** [comment]
When including PySide, PyInstaller breaks the boost::lexical_cast ... WTF !

Without PySide, the executable produced by PyInstaller works fine. I'm looking for a workaround.

**Comment by Theverat** [comment]
Hm... how hard would it be to switch to PyQt at this point?

**Comment by Dade916** [comment]
It not only breaks boost::lexical_cast but just C++ std::stringstream. This i pretty much a nail in the coffin of any possible workaround...

**Comment by Dade916** [comment]
I will have to change the way pyluxcoretool is run on Linux. All alternatives to PyInstaller are Windows-only as far as I can see. This is going to be cumbersome for all Linux users.

**Comment by Dade916** [comment]
Ok, as workaround, you can now run pyluxcoretool with a (update LuxCore and LinuxCompile):

python3 pyluxcoretools.zip

This should be simple enough to be usable. Indeed, you have to install by hand PySide with a:

pip3 install PySide

because it lacks the standalone environment of PyInstaller but it should be ok.

Let me know if it works for you.

**Comment by Theverat** [comment]
Yes, it works if I start it that way.
